services:
  web-server:
    build: ./web-server
    image: web-server:latest
    container_name: web-server
    hostname: web-server
    volumes:
      - ./web-server:/opt/web-server
    ports:
      - 3000:3000

  api-server:
    build: ./api-server
    image: api-server:latest
    container_name: api-server
    hostname: api-server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres
    volumes:
      - ./api-server:/opt/api-server
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: database
    hostname: database
    platform: linux/amd64
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-data:
